version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto24
    commands:
      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
  pre_build:
    commands:
      - mvn clean compile test
  build:
    commands:
      - mvn package
  post_build:
    commands:
      # Do not remove this statement. This command is required for AWS CodeStar projects.
      - echo Build completed
artifacts:
  files:
    - 'appspec.yml'
    - 'scripts/*'
    - 'target/ROOT.war'
